### ISSUE TITLE
数据集制作

### ISSUE THREAD

**Issue by kongyan66** [ming71/OBBDet_Swin#3]
请问下作者数据集怎么制作的，是转为mmdet中间格式(.pkl)还是转为dota格式的，我之前转为mmdet中间格式（.pkl）网络并不能收敛。所以这个赛道弃赛了。还有这是全部开源代码吗？我想完整跑一下，弥补下遗憾，希望得到您的解答，谢谢！

**Comment by ming71** [comment]
1. 这个代码提供了接口将FAIR1M的数据转化为dota格式，进而按照dota数据训练即可
2. 这部分代码基本囊括了我们的实现方案。还有一个redet可以参考https://github.com/csuhan/ReDet
3. 祝顺利。

**Comment by kongyan66** [comment]
你好，再次打扰了，请问作者所说将FAIR1M的数据转化为dota格式的接口，代码具体在哪呢？我并没有找到呀

**Comment by sunny-sjj** [comment]
> 你好，再次打扰了，请问作者所说将FAIR1M的数据转化为dota格式的接口，代码具体在哪呢？我并没有找到呀

请参考[fair_to_dota](https://github.com/sunny-sjj/OBBDet_Swin/blob/master/tools/fair_to_dota.py)

**Comment by kongyan66** [comment]
@sunny-sjj 感谢

**Comment by kongyan66** [comment]
@sunny-sjj 请问这个转换脚本是你写的吗？因为我在作者repo并没有找到，训练时候会loss为Nan吗？我之前就是这个问题，方便的话可以加微信聊下吗，我自己做旋转数据集转DOTA总容易出现这种问题。

**Comment by sunny-sjj** [comment]
@kongyan66 好的，我的号发你github上挂的邮箱了

**Comment by gggzq** [comment]
你好，问下数据切割是用的OBB官方的BboxToolkit里面的img_split吗？还有一个问题是你们在做离线数据增强是整张大图做还是在小图切割了做的？@sunny-sjj @ming71

**Comment by sunny-sjj** [comment]
@gggzq 
1.数据切割是在BboxToolkit按照size=800,gap=200里面进行切割的。
2.离线增强是在先在原图上数据增强，然后再切割。

**Comment by sunny-sjj** [comment]
@gggzq 
1.我们是在BboxToolkit按照size=800,gap=200进行切割的。
2.在作离线增强的时候，是先在原图数据增强，然后再切割的。

**Comment by gggzq** [comment]
**谢谢** @sunny-sjj
