### ISSUE TITLE
FAIR1M数据集增强

### ISSUE THREAD

**Issue by fffucla** [ming71/OBBDet_Swin#6]
您好，我想请问您在对FAIR1M数据集做数据增强的时候使用的是toolbox里面的smart_augment.py吗？如果直接用原图进行增强的话，我使用时每一张图片的增强产生的数量实在是太多了，感觉不太对，请问您当时比赛的时候具体是使用了toolbox中的哪一个文件如何进行的增强呢，十分想完成一下复现，感谢了！（同时我看您博文中提到了随机缩放的方法，请问它对应的增强函数是哪一个呀？）

如果方便，希望能跟您加个微信学习一下！！

**Comment by ming71** [comment]
抱歉现在看到你的问题。
比赛时采用smart_augment对小样本的类别进行了重采样，并加了一些离线增强。
同时训练的时候有了OBBDet内置的一些在线增强。
