### ISSUE TITLE
请问您是用那个版本的swin tranformer的预训练权重，我用torch1.4的版本 

### ISSUE THREAD

**Issue by 2324773711** [ming71/OBBDet_Swin#8]

**Comment by 2324773711** [comment]
请问您是用那个版本的swin tranformer的预训练权重，我用torch1.4的版本

**Comment by 2324773711** [comment]
请问您是用那个版本的swin tranformer的预训练权重，我用torch1.4的版本 。如果有低版本的swin tranformer的预训练权重可以给我发一下吗？非常感谢

**Comment by ming71** [comment]
预训练权重就是官方提供的。
我当时好像是1.2还是1.6记不清了，这个影响不大，最多就是改点不兼容的地方就行。
